Repository FarmorAI/farm-web-react, pull requests merged in 2025-02, with the labels that each got.

#13 Hoon2
  eslint.config.js
  package-lock.json
  package.json
  src/api/boardApi.ts
  src/api/noticeApi.ts
  src/components/ai/uploadform/FileUploader.tsx
  src/components/ai/uploadform/RatingSection.tsx
  src/components/ai/uploadform/Step.tsx
  src/components/contents/CommonContents.tsx
  src/components/contents/PageComponent.tsx
  src/components/contents/Pagination.tsx
  src/components/contents/TableComponent.tsx
  src/components/contents/WriteForm.tsx
  src/components/contents/board/BoardDetail.tsx
  src/components/contents/board/BoardList.tsx
  src/components/contents/notice/NoticeDetail.tsx
  src/components/contents/notice/NoticeList.tsx
  src/components/pagelayout/MenuData.ts
  src/hook/contents/useNotices.ts
  src/hook/useMove.ts
  src/main.tsx
  src/model/contents.ts
  src/pages/ai/AIUploadPage.tsx
  src/pages/ai/UploadFormPage.tsx
  src/pages/ai/UploadListPage.tsx
  src/pages/ai/UploadResultPage.tsx
  src/pages/contents/board/BoardDetailPage.tsx
  src/pages/contents/board/BoardWritePage.tsx
  src/pages/contents/notice/NoticeWritePage.tsx
  src/pages/support/SupportEmailPage.tsx
  src/router/AiRouter.tsx
  src/router/BoardRouter.tsx
  src/router/ContentsRouter.tsx
  src/router/Root.tsx
Labels: enhancement

#15 Feature/payment result
  src/api/paymentApi.ts
  src/components/pagelayout/MenuData.ts
  src/model/subscription.ts
  src/pages/payment/PaymentPage.tsx
  src/pages/payment/PaymentResultPage.tsx
  src/router/PaymentRouter.tsx
  vite.config.ts
Labels: enhancement

#19 Feature/ai result
  .gitignore
  .md
  package-lock.json
  package.json
  public/assets/images/kakao_login.png
  src/api/authApi.ts
  src/api/boardApi.ts
  src/api/memberApi.ts
  src/api/noticeApi.ts
  src/api/paymentApi.ts
  src/api/socialApi.ts
  src/api/uploadApi.ts
  src/components/ai/uploadresult/GrowthChart.tsx
  src/components/ai/uploadresult/HarvestChart.tsx
  src/components/ai/uploadresult/HealthChart.tsx
  src/components/ai/uploadresult/QualityChart.tsx
  src/components/auth/KaKaoLoginComponent.tsx
  src/components/register/AddressFields.tsx
  src/components/register/InputField.tsx
  src/components/register/RegisterForm.tsx
  src/components/register/TermsAgreement.tsx
  src/components/section/Header.tsx
  src/hook/register/useValid.ts
  src/hook/useDropdown2.ts
  src/main.tsx
  src/model/contents.ts
  src/pages/ai/UploadResultPage.tsx
  src/pages/auth/KaKaoRedirectPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/auth/RegisterPage.tsx
  src/pages/contents/board/BoardWritePage.tsx
  src/pages/contents/notice/NoticeWritePage.tsx
  src/redux/slices/authslices.ts
  src/redux/store.ts
  src/router/AuthRouter.tsx
  src/util/cookieUtill.ts
  tailwind.config.cjs
  vite.config.ts
Labels: bug

#23 Redux
  src/api/authApi.ts
  src/api/boardApi.ts
  src/api/memberApi.ts
  src/api/socialApi.ts
  src/components/contents/CommonContents.tsx
  src/components/pagelayout/MenuData.ts
  src/components/section/Header.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/support/SupportCustomerPage.tsx
  src/pages/support/SupportEmailPage.tsx
  src/redux/slices/authslices.ts
  src/router/SupportRouter.tsx
Labels: enhancement

#25 Feature/google login
  .env
  .gitignore
  public/assets/images/google_login.png
  src/api/socialApi.ts
  src/components/auth/GoogleLoginComponent.tsx
  src/pages/auth/GoogleRedirectPage.tsx
  src/pages/auth/LoginPage.tsx
  src/router/AuthRouter.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: good first issue
