Repository FarmorAI/farm-web-react, pull requests merged in 2025-03, with the labels that each got.

#31 Redux
  .md
  src/api/authApi.ts
  src/components/section/Header.tsx
  src/hook/useDropdown.tsx
  src/pages/auth/KaKaoRedirectPage.tsx
  src/pages/auth/ProfilePage.tsx
  src/pages/auth/RegisterPage.tsx
  src/redux/slices/authslices.ts
  src/router/AuthRouter.tsx
Labels: enhancement

#33 로고 변경
  public/assets/images/auth/20250301_173622.png
  public/assets/images/auth/google.png
  public/assets/images/auth/kakao.png
  public/assets/images/auth/naver.png
  public/assets/images/google_login.png
  public/assets/images/kakao_login.png
  public/assets/images/logo/headerlogo.png
  public/assets/images/logo/headerlogo1.png
  public/assets/images/logo/logo.png
  public/assets/images/member/다혜.png
  public/assets/images/member/도훈.png
  public/assets/images/member/종범.png
  public/assets/images/member/준명.png
  public/assets/images/naver_login.png
  src/components/auth/GoogleLoginComponent.tsx
  src/components/auth/KaKaoLoginComponent.tsx
  src/components/auth/NaverLoginComponent.tsx
  src/components/section/Footer.tsx
  src/components/section/Header.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/introduce/TeamPage.tsx
  src/pages/practice/Prac.tsx
  src/pages/practice/Pract.tsx
  src/pages/practice/Practice.tsx
  src/pages/practice/chart/BarChart.tsx
  src/pages/practice/chart/Chart.tsx
  src/pages/practice/chart/ChartJsExample.tsx
  src/pages/practice/chart/DoughnutChart.tsx
  src/pages/practice/chart/RechartsExample.tsx
Labels: enhancement

#39 Hoon100
  .md
  package-lock.json
  package.json
  public/assets/images/google (2).png
  public/assets/images/introduce/introduce1.png
  public/assets/images/introduce/introduce2.png
  public/assets/images/introduce/introduce3.png
  public/assets/images/introduce/딸기ai분석.jpg
  public/assets/images/kakao.png
  public/assets/images/logo/headerlogo.png
  public/assets/images/logo/headerlogo1.png
  public/assets/images/logo/logo.png
  public/assets/images/naver.png
  src/api/boardApi.ts
  src/api/noticeApi.ts
  src/api/supportApi.ts
  src/components/contents/CommonContents.tsx
  src/components/contents/CommonList.tsx
  src/components/contents/DetailComponent.tsx
  src/components/contents/ListComponent.tsx
  src/components/contents/board/BoardDetail.tsx
  src/components/contents/board/BoardList.tsx
  src/components/contents/notice/NoticeDetail.tsx
  src/components/contents/notice/NoticeList.tsx
  src/components/contents/support/SupportDetail.tsx
  src/components/contents/support/SupportList.tsx
  src/components/pagelayout/Breadcrumbs.tsx
  src/components/pagelayout/MenuData.ts
  src/components/section/Footer.tsx
  src/components/section/Header.tsx
  src/hook/contents/useFetchDetail.ts
  src/hook/contents/useFetchList.ts
  src/hook/contents/useFetchUpdate.ts
  src/main.css
  src/model/contents.ts
  src/pages/auth/KaKaoRedirectPage.tsx
  src/pages/auth/LoginPage.tsx
  src/pages/contents/board/BoardDetailPage.tsx
  src/pages/contents/board/BoardListPage.tsx
  src/pages/contents/board/BoardWritePage.tsx
  src/pages/contents/notice/NoticeDetailPage.tsx
  src/pages/contents/notice/NoticeListPage.tsx
  src/pages/introduce/ProjectPage.tsx
  src/pages/introduce/TeamPage.tsx
  src/pages/support/SupportDetailPage.tsx
  src/pages/support/SupportListPage.tsx
  src/pages/weather/InfoDisplay.tsx
  src/router/AuthRouter.tsx
Labels: enhancement

#42 Feature/inquiry
  src/api/supportApi.ts
  src/hook/useMove.ts
  src/model/support.ts
  src/pages/support/SupportCustomerPage.tsx
  src/pages/support/SupportForm.tsx
Labels: bug

#47 Songbeom00
  package-lock.json
  src/components/auth/profile/AnalysisChart.tsx
  src/components/auth/profile/AnalysisGallery.tsx
  src/components/auth/profile/ProfileCard.tsx
  src/components/auth/profile/PurchasedHistory.tsx
  src/components/pagelayout/Breadcrumbs.tsx
  src/components/product/ProductCart.tsx
  src/components/product/ProductDetail.tsx
  src/components/product/ProductList.tsx
  src/components/section/Header.tsx
  src/hook/auth/useProfile.ts
  src/hook/product/useProductCart.ts
  src/hook/product/useProductDetail.ts
  src/hook/product/useProductList.ts
  src/model/product.ts
  src/pages/auth/FindPage.tsx
  src/pages/auth/ProfilePage.tsx
  src/pages/payment/CartResultPage.tsx
  src/pages/product/ProductCartPage.tsx
  src/pages/product/ProductDetailPage.tsx
  src/pages/product/ProductListPage.tsx
  src/pages/product/ProductRegisterPage.tsx
  src/router/PaymentRouter.tsx
  src/router/ProductRouter.tsx
Labels: good first issue

#48 cart, order result page
  src/components/auth/profile/PurchasedHistory.tsx
  src/components/product/ProductCart.tsx
  src/hook/auth/useProfile.ts
  src/model/product.ts
  src/pages/auth/ProfilePage.tsx
  src/pages/payment/CartResultPage.tsx
  src/pages/product/ProductRegisterPage.tsx
Labels: good first issue

#49 Hoon100
  package-lock.json
  package.json
  public/assets/images/introduce/apple1.jpg
  public/assets/images/introduce/apple2.png
  public/assets/images/introduce/apple3.jpg
  public/assets/images/introduce/introduce1.png
  public/assets/images/introduce/introduce3.png
  public/assets/images/introduce/딸기ai분석.jpg
  public/assets/images/introduce/사과ai분석.png
  public/assets/images/logo/applepick.png
  src/components/auth/LoginForm.tsx
  src/components/auth/profile/ProfileEditModal.tsx
  src/components/pagelayout/MenuData.ts
  src/components/pagelayout/Sidebar.tsx
  src/components/product/ProductRegister.tsx
  src/components/section/Footer.tsx
  src/components/section/Header.tsx
  src/hook/auth/useProfile.ts
  src/hook/product/useProductRegister.ts
  src/pages/auth/ProfilePage.tsx
  src/pages/introduce/ProjectPage.tsx
  src/pages/introduce/TeamPage.tsx
  src/pages/product/ProductRegisterPage.tsx
  src/pages/weather/Banner.tsx
Labels: enhancement

#50 Feature/admin
  src/components/ai/uploadform/FileUploader.tsx
  src/components/contents/ListComponent.tsx
  src/hook/useMove.ts
  src/pages/ai/UploadFormPage.tsx
  src/router/SupportRouter.tsx
Labels: bug, enhancement

#51 update mypage subs
  public/assets/images/subs/apple_basic.png
  public/assets/images/subs/gold_premium.png
  src/api/authApi.ts
  src/api/paymentApi.ts
  src/components/auth/profile/SubscriptionCard.tsx
  src/components/auth/profile/SubscriptionModal.tsx
  src/components/section/Header.tsx
  src/pages/auth/ProfilePage.tsx
  src/pages/weather/WeatherDisplay.tsx
Labels: bug, enhancement

#52 Hoon100
  src/components/auth/LoginForm.tsx
  src/components/auth/profile/ProfileCard.tsx
  src/components/auth/profile/ProfileEditModal.tsx
  src/components/auth/social/GoogleLoginComponent.tsx
  src/components/auth/social/KaKaoLoginComponent.tsx
  src/components/auth/social/NaverLoginComponent.tsx
  src/components/pagelayout/MenuData.ts
  src/components/section/Footer.tsx
  src/components/section/Header.tsx
  src/pages/introduce/ProjectPage.tsx
  src/pages/introduce/TeamPage.tsx
  src/router/SupportRouter.tsx
Labels: enhancement

#54 Hoon100
  package-lock.json
  package.json
  public/assets/images/logo/apple.png
  src/api/boardApi.ts
  src/api/memberApi.ts
  src/components/auth/profile/DeleteAccountModal.tsx
  src/components/auth/profile/OrderStatusCounts.tsx
  src/components/auth/profile/ProfileCard.tsx
  src/components/auth/profile/ProfileEditModal.tsx
  src/components/auth/profile/PurchasedHistory.tsx
  src/components/auth/profile/SubscriptionModal.tsx
  src/components/contents/WriteForm.tsx
  src/components/pagelayout/Carousel.tsx
  src/components/product/ProductCart.tsx
  src/components/section/Footer.tsx
  src/components/support/SupportForm.tsx
  src/hook/auth/profile/useProfileCard.ts
  src/hook/auth/profile/usePurchaseHistory.ts
  src/hook/contents/useFetchUpdate.ts
  src/hook/product/useProductCart.ts
  src/model/product.ts
  src/pages/auth/ProfilePage.tsx
  src/pages/contents/board/BoardUpdatePage.tsx
  src/pages/contents/board/BoardWritePage.tsx
  src/pages/contents/notice/NoticeUpdatePage.tsx
  src/pages/product/ProductCartPage.tsx
  src/pages/support/SupportCustomerPage.tsx
  src/pages/support/SupportUpdatePage.tsx
  src/pages/weather/Banner.tsx
  src/router/ContentsRouter.tsx
Labels: enhancement

#55 Feature/subs
  src/api/aiApi.ts
  src/api/paymentApi.ts
  src/components/ai/uploadform/Step.tsx
  src/components/auth/profile/SubscriptionCard.tsx
  src/components/auth/profile/SubscriptionModal.tsx
  src/components/pagelayout/MenuData.ts
  src/model/subscription.ts
  src/pages/ai/UploadFormPage.tsx
  src/pages/ai/UploadListPage.tsx
  src/pages/payment/PaymentPage.tsx
  src/pages/payment/PaymentResultPage.tsx
  src/pages/payment/SubsCard.tsx
Labels: enhancement

#57 Songbeom00
  .dockerignore
  .env.production
  .gitignore
  Dockerfile
  nginx/nginx.conf
  src/components/product/ProductCart.tsx
  src/components/product/ProductDetail.tsx
  src/hook/product/useProductCart.ts
  src/hook/product/useProductDetail.ts
  src/model/contents.ts
  src/pages/product/ProductDetailPage.tsx
  src/pages/weather/GraphDisplay.tsx
  src/pages/weather/TechDisplay.tsx
Labels: enhancement, good first issue

#61 good
  src/pages/weather/GraphDisplay.tsx
Labels: enhancement

#62 Songbeom00
  Dockerfile
  nginx/nginx.conf
  src/components/product/ProductCart.tsx
  src/hook/product/useProductList.ts
  vite.config.ts
Labels: enhancement

#63 Songbeom00
  src/api/aiApi.ts
  src/pages/ai/UploadListPage.tsx
  src/pages/ai/UploadResultPage.tsx
Labels: enhancement, good first issue
